ARG SHARELATEX_BASE_TAG=sharelatex/sharelatex:latest
FROM $SHARELATEX_BASE_TAG

# Install xeLatex and CJK 
RUN  apt-get install -y texlive-lang-cjk texlive-xetex texlive-luatex
# Add supports for new fonts cache generation
COPY ./hotfix/97_generate_font_cache.sh /etc/my_init.d/97_generate_font_cache.sh

# Install axios library for OAuth2
RUN npm install axios --save
COPY ./hotfix/AuthenticationController.js /overleaf/services/web/app/src/Features/Authentication/AuthenticationController.js
COPY ./hotfix/AuthenticationManager.js /overleaf/services/web/app/src/Features/Authentication/AuthenticationManager.js
COPY ./hotfix/router.js /overleaf/services/web/app/src/router.js
COPY ./hotfix/login.pug /overleaf/services/web/app/views/user/login.pug
COPY ./hotfix/footer.pug /overleaf/services/web/app/views/layout/footer.pug
COPY ./hotfix/footer-marketing.pug /overleaf/services/web/app/views/layout/footer-marketing.pug